config/routes.rb
Antibodyapp::Application.routes.draw do
  resources :validators
  resources :projects
  resources :targets do
    get :autocomplete_target_name, :on => :collection
    get :search, :on => :collection
  end
  resources :sources
  devise_for :users
  resources :users
  resources :species
  resources :antibodies
  root :to => "pages#home"
  match 'about' => "pages#about"
  match 'upload' => "pages#upload"
  match 'create_validator' => "pages#create_validator"
  match 'create_validation' => "pages#create_validation"
  match 'create_target' => "pages#create_target"
  match 'create_source' => "pages#create_source"
  match 'create_antibody' => "pages#create_antibody"
  match 'set_validator' => "pages#set_validator"

end

app/views/pages/_antibodies.html.erb
<div id="select_antibody">
  <h3>Select an antibody (or <%= link_to "create a new one", upload_url(:target_id => @target.id, :new_antibody => 1) %>):</h3>
  <table>
    <tr>
      <th>Source</th>
      <th>Catalogue #</th>
      <th>Lot #</th>
      <th>Select</th>
    </tr>
    <% for item in @target.antibodies %>
    <tr>
      <td><%= item.source.name %></td>
      <td><%= item.catalogue_number %></td>
      <td><%= item.lot_number %></td>
      <td><%= link_to("Select", upload_url(:target_id => @target, :antibody_id => item))%></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/_new_antibody.html.erb
<div id="create_antibody">
<%= link_to("Select from existing antibodies", upload_url(:target_id => @target.id))%>
<% if @source.nil? %>
  <h3>Find the source (company or lab) of your new antibody:</h3>
    <%= form_tag upload_url, :method => 'get', :class => "upload" do %>
      <%= hidden_field_tag :target_id, @target.id %>
      <%= hidden_field_tag :new_antibody, 1 if params[:new_antibody] %>
      <%= text_field_tag :find_source, params[:find_source], :id => "upload_source_search" %>
      <%= submit_tag "search", :name => nil%>
    <% end %>
    Examples: <%= Source.most_antibodies.limit(5).map {|s| link_to(s.name, upload_url(:find_source => s.name, :target_id => @target.id, :new_antibody => 1))}.join(", ").html_safe %>
    <% if @sources.present? %>
      <%= render 'sources' %>
    <% elsif params[:find_source].present? %>
      <%= render 'new_source'%>
    <% end %>
  
<% else %>
  <h3>Create a new antibody:</h3>
  
  <%= form_for(@new_antibody, :url => create_antibody_url, :html => {:class => "upload"}) do |f| %>
    <%= f.hidden_field :target_id %>
    <%= f.hidden_field :source_id %>
    <% if @new_antibody.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@new_antibody.errors.count, "error") %> prohibited this antibody from being saved:</h2>

        <ul>
        <% @new_antibody.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :source %> <span class="selected"><%= @source.name %></span>
    </div>
    <div class="field">
      <%= f.label :catalogue_number, "Catalogue #" %> <%= f.text_field :catalogue_number, :class => "long" %>
    </div>
    <div class="field">
      <%= f.label :lot_number, "Lot #" %> <%= f.text_field :lot_number, :class => "long" %>
    </div>

    <div class="field">
      <%= f.label :host_species_id, "Host Species" %> <%= f.select :host_species_id, options_from_collection_for_select(Species.order("targets_count desc, name"), :id, :name) %>
    </div>
    <div class="field">
      <%= f.label :clonality %> <%= f.radio_button :clonality, "monoclonal" %> <%= f.label :clonality_monoclonal, "Monoclonal", :class => "radio" %> <%= f.radio_button :clonality, "polyclonal" %> <%= f.label :clonality_polyclonal, "Polyclonal", :class => "radio" %>
    </div>
    <div class="field">
      <%= f.label :purification %> <%= f.select :purification, ["Affinity", "Crude", "Partial", "Protein A", "Protein G", "Serum", "Tissue Culture Supernatant"].sort %>
    </div>
    <div class="field">
      <%= f.label :url, "Product Website" %> <%= f.text_field :url, :class => "long" %>
      <div class="examples" style="display: block">e.g. http://www.abcam.com/Histone-H3-tri-methyl-K9-antibody-ChIP-Grade-ab8898.html </div>
    </div>
    <div class="actions">
      <%= f.submit("save", :class => "right") %>
    </div>
  <% end %>
<% end %>
</div>

app/views/pages/_new_source.html.erb
<h3>No sources found for "<%= params[:find_source]%>". Let's create a new one:</h3>

<%= form_for(@new_source, :url => create_source_url(:target_id => @target.id), :html => {:class => "upload"} ) do |f| %>
  <% if @new_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_source.errors.count, "error") %> prohibited this source from being saved:</h2>

      <ul>
      <% @new_source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Source Name" %>
    <%= f.text_field :name, :class => "long" %>
  </div>

  <div class="actions">
    <%= f.submit("save", :class => "right") %>
  </div>
<% end %>

app/views/pages/_new_target.html.erb
<h3>No targets found for "<%= params[:find_target]%>". Let's create a new one:</h3>

<%= form_for(@new_target, :url => create_target_url, :html => {:class => "upload"} ) do |f| %>
  <% if @new_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @new_target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :species_id, "Target Species" %>
    <%= f.select :species_id, options_from_collection_for_select(Species.order("targets_count desc, name"), :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :name, "Target Name" %>
    <%= f.text_field :name, :class => "long" %>
  </div>

  <div class="actions">
    <%= f.submit("save", :class => "right") %>
  </div>
<% end %>

app/views/pages/_sources.html.erb
<% if @sources.present? %>
<h3>Select a source:</h3>
<ul class="upload">
  <% for source in @sources %>
    <li><%= link_to source.name, upload_url(:source_id => source.id, :target_id => @target.id, :new_antibody => params[:new_antibody])%></li>
  <% end %>
</ul>
<% end %>

app/views/pages/_targets.html.erb
<% if @targets.present? %>
<h3>Select a target:</h3>
<ul class="upload">
  <% for target in @targets %>
    <li><%= link_to target.name_with_species, upload_url(:target_id => target.id)%></li>
  <% end %>
</ul>
<% end %>

app/views/pages/about.html.erb
<h1>About Us</h1>




<div class="yui3-g">
  <div class="yui3-u-1-2">
    <div class="left">
      <h2>Purpose</h2>
      <p>Many biological studies rely on high-quality antibodies, but many commercial antibodies do not perform well (more than a quarter of the <%= link_to "histone antibodies", project_path(1) %> tested in <%= link_to "Egelhofer et al.", "http://dx.doi.org/10.1038/nsmb.1972", :target => "_blank" %> fail a validation test). The problem is compounded by a lack of uniform standard and the laborious steps required for full validation. The aim of this site is to collect and to share experimental results on antibodies that would otherwise remain in individual laboratories, thus aiding researchers in selection and validation of antibodies. This site began with 200+ histone antibodies tested as part of the <%= link_to "ENCODE", "http://www.genome.gov/10005107", :target => "_blank" %> (Encyclopedia of DNA Elements) and <%= link_to "Roadmap Epigenomics", "http://www.roadmapepigenomics.org/", :target => "_blank" %> projects (non-histone antibodies from the same projects will be added shortly).  We invite the scientific community to contribute their data.</p>

      <h2>Validation criteria</h2>
      <p>Please see <%= link_to "this document", root_url + "documents/30MAY2010_mod-ENCODE_TF_Chrom_Data_Standards.pdf", :target => "_blank" %> on data standards (Appendix II for antibody validation) from the <%= link_to "ENCODE", "http://www.genome.gov/10005107", :target => "_blank" %> and <%= link_to "modENCODE", "http://www.modencode.org/", :target => "_blank" %> consortia.
      For the <%= link_to "histone antibodies", project_path(1) %> in <%= link_to "Egelhofer et al.", "http://dx.doi.org/10.1038/nsmb.1972", :target => "_blank" %>, the following simplified criteria were used.</p>
      
      <ul class="about">
        <li><strong>Western blot</strong>: Pass if the histone band constituted at least 50% of the total nuclear signal, was at least ten-fold more intense than any other single nuclear band, and was at least ten-fold more intense than recombinant, unmodified histone.</li>
        <li><strong>Dot blot</strong>: Pass if at least 75% of the total signal was specific to the cognate peptide.</li>
        <li><strong>ChIP-chip/seq</strong>:  Pass if the Pearson correlation is more than 0.8 on any pair of ChIPs performed from independent preparations matched for stage, cell type or biological tissue</li>
      </ul>
    </div>
  </div>
    
  <div class="yui3-u-1-2">
    <div class="right">
      <h2>Notes on use of the database</h2>
      <p>It is important to note that there is significant variability between different lots of the same polyclonal antibody. The quality of experiments may also be variable depending on experimentalist. Thus, the users should take the validation data here as a guide, to be further verified (and deposited!).</p>
      <h2>How to cite us</h2>
      <p>Egelhofer et al, An assessment of histone-modification antibody quality, <em>Nature Structural & Molecular Biology, 2010</em>, <%= link_to "doi:10.1038/nsmb.1972", "http://dx.doi.org/10.1038/nsmb.1972", :target => "_blank" %></p>

      <h2>Funding</h2>
      <p>This website was developed with funding from the <%= link_to "model organism ENCODE", "http://www.modencode.org/", :target => "_blank" %>, <%= link_to "human ENCODE", "http://www.genome.gov/10005107", :target => "_blank" %>, and <%= link_to "Roadmap Epigenomics", "http://www.roadmapepigenomics.org/", :target => "_blank" %> projects by <%= link_to "NIH", "http://www.nih.gov", :target => "_blank" %>.</p>
      <p><%= image_tag("modencode_roadmapepigenomics.png")%></p>
      
      <h2>Contact information</h2>
      <p>This website is maintained by the <%= link_to "Park laboratory", "http://compbio.med.harvard.edu/", :target => "_blank" %> at the <%= link_to "Center for Biomedical Informatics", "http://cbmi.med.harvard.edu", :target => "_blank" %> at <%= link_to "Harvard Medical School", "http://hms.harvard.edu/", :target => "_blank" %>. Database and website design is by <%= link_to "Kyungjoon Lee", "mailto:joon_lee@hms.harvard.edu", :target => "_blank" %>. Please contact <%= link_to "joon_lee@hms.harvard.edu", "mailtojoon_lee@hms.harvard.edu", :target => "_blank" %> and <%= link_to "peter_park@harvard.edu", "mailto:peter_park@harvard.edu", :target => "_blank" %> with questions and suggestions, noting ‘[antibody]’ in the subject line.  You may also direct correspondence to Jason Lieb (<%= link_to "jlieb@bio.unc.edu", "mailto:jlieb@bio.unc.edu", :target => "_blank" %>; for C. elegans), R. David Hawkins (<%= link_to "d1hawkins@ucsd.edu", "mailto:d1hawkins@ucsd.edu", :target => "_blank" %>; for human) or Gary Karpen (<%= link_to "karpen@fruitfly.org", "mailto:karpen@fruitfly.org", :target => "_blank" %>; for D. melanogaster).</p>
      
  </div>
</div>

app/views/pages/home.html.erb
<div id="searchhome" class="home">
  <form method="get" action="<%= targets_url %>" id="searchform">
    <input type="hidden" name="id" id="autocompleted_id">
    <input type="text" name="q" data-autocomplete="<%= autocomplete_target_name_targets_url %>" id_element="#autocompleted_id" id="target_search_query">
    <input type="submit" value="search" id="searchsubmit">
    <p>Search examples: <%= Target.most_validated.limit(3).map {|t| link_to(t.name, targets_url(:q => t.name))}.join(", ").html_safe %></p>
  </form>
</div>

<div class="yui3-g">
  <div class="yui3-u-1-2">
    <div class="left">
      <div class="dashboard">
        <ul>
          <li>
            <span class="value"><%= link_to number_with_delimiter(Target.count), targets_path %></span>
            <span class="item">targets</span>
          </li>
          <li>
            <span class="value"><%= link_to number_with_delimiter(Antibody.count), antibodies_path %></span>
            <span class="item">antibodies</span>
          </li>
          <li>
            <span class="value"><%= link_to number_with_delimiter(Species.where("targets_count > 0").count), species_index_path %></span>
            <span class="item">species</span>
          </li>
          <li>
            <span class="value"><%= link_to number_with_delimiter(Source.count), sources_path %></span>
            <span class="item">sources</span>
          </li>
          <li>
            <span class="value"><%= link_to number_with_delimiter(Validator.count), validators_path %></span>
            <span class="item">validators</span>
          </li>
          <li>
            <span class="value"><%= link_to number_with_delimiter(Project.count), projects_path %></span>
            <span class="item">project</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
    
  <div class="yui3-u-1-2">
    <div class="right">
      <div class="banner"><%= link_to "Histone Modification Antibodies from Egelhofer et al, An assessment of histone-modification antibody quality, Nature Structural & Molecular Biology, 2010", project_path(1)%></div>     
    </div>
  </div>
</div>

app/views/pages/set_validator.html.erb
<h1>Set Up Your Validating Lab</h1>

<%= form_tag set_validator_url, :method => 'post', :class => "upload" do %>
  <%= label_tag :validator_id, "Validator name" %>
  <%= select_tag :validator_id, options_from_collection_for_select(Validator.order("name"), :id, :name, current_user.validator_id) %>
  
  <%= submit_tag "save", :name => nil%>
<% end %>

<h2>Create New Validating Lab</h2>

<%= form_tag create_validator_url, :method => 'post', :class => "upload" do %>
  <%= label_tag :validator_name %>
  <%= text_field_tag :validator_name, params[:validator_name] %>
  <%= submit_tag "save", :name => nil%>
<% end %>

app/views/pages/upload.html.erb
<h1>Upload New Validation Data</h1>

<h2>Step 1. Find Target: <span class="selected"><%= @target.try(:name_with_species) %></span></h2>
<% if @target.present? %>
  <%= link_to("Find another target", upload_url) %>
<% else %>
  <h3>Find the target of your antibody:</h3>
  <%= form_tag upload_url, :method => 'get', :class => "upload" do %>
    <%= text_field_tag :find_target, params[:find_target], :id => "upload_target_search" %>
    <%= submit_tag "Search", :name => nil%>
  <% end %>
  Examples: <%= Target.most_validated.limit(3).map {|t| link_to(t.name, upload_url(:find_target => t.name))}.join(", ").html_safe %>
  <div id="targets">
    <% if @targets.present? %>
      <%= render 'targets' %>
    <% elsif params[:find_target].present? %>
      <%= render 'new_target'%>
    <% end %>
  </div>
<% end %>

<h2>Step 2. Find Antibody: <span class="selected"><%= @antibody.try(:source_with_catalogue_and_lot_number)%></span></h2>
<% if @target.present? and @antibody.nil? %>
  <% if @target.antibodies.size > 0 and params[:new_antibody].nil? %>
    <%= render 'antibodies' %>
  <% end %>
  <%= render 'new_antibody' if params[:new_antibody].present? %>
<% end %>

<%= link_to("Find another antibody", upload_url(:target_id => @target)) if @antibody.present? %>


<h2>Step 3. Upload Validation</h2>
<% if @target.present? and @antibody.present? %>
  <%= form_for(@validation, :url => create_validation_url, :html => {:multipart => true, :class => "upload"}) do |f| %>
    <%= f.hidden_field :target_id %>
    <%= f.hidden_field :antibody_id %>
    <%= f.hidden_field :validator_id %>
    <% if @validation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@validation.errors.count, "error") %> prohibited this validation from being saved:</h2>

        <ul>
        <% @validation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :validated_species %>
      <%= f.select :species_id, options_from_collection_for_select(Species.order("targets_count desc"), :id, :name) %>
    </div>
    <div class="field">
      <%= f.label :category %>
      <%= f.radio_button :category, "Western blot" %> <%= f.label :category_western_blot, "Western blot", :class => "radio" %>
      <%= f.radio_button :category, "Dot blot" %> <%= f.label :category_dot_blot, "Dot blot", :class => "radio"  %>
      <%= f.radio_button :category, "ChIP-chip/seq" %> <%= f.label "category_chip-chipseq", "ChIP-chip/seq", :class => "radio"  %>
    </div>
    <div class="field">
      <%= f.label :result %> <%= f.radio_button :passed, 1 %> <%= f.label :passed_1, "Passed", :class => "radio"%>
      <%= f.radio_button :passed, 0 %> <%= f.label :passed_0, "Failed", :class => "radio"%><%= validation_criteria_help.html_safe %>
    </div>
    <div class="field">
      <%= f.label :notes %>
      <%= f.text_field :notes, :class => "long" %>
      <div class="examples" id="validation_category_western_blot_example">e.g. "Single histone band" or "Histone + other bands"</div>
      <div class="examples" id="validation_category_dot_blot_example">e.g. "Specific (90%); Cross-reacting peptides: H3K36me2 (<10%)"</div>
      <div class="examples" id="validation_category_chip-chipseq_example">e.g. "Marketed as ChIP grade"</div>
    </div>
    <div class="field">
      <%= f.label :conditions %>
      <%= f.text_field :conditions, :class => "long" %>
      <div class="examples" id="validation_conditions_example">e.g. "0.5 ug/ml ON at 4C" or "1:2000 ON at 4C"</div>
    </div>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image, :accept => 'image/png,image/gif,image/jpeg' %>
    </div>
    <div class="field">
      <%= f.label :validator_name %>
      <%= f.text_field :validator_name, :class => "long" %>
    </div>
    <div class="actions">
      <%= f.submit("save", :class => "right") %>
    </div>
  <% end %>
<% end %>