config/routes.rb
Antibodyapp::Application.routes.draw do
  resources :validators
  resources :projects
  resources :targets do
    get :autocomplete_target_name, :on => :collection
    get :search, :on => :collection
  end
  resources :sources
  devise_for :users
  resources :users
  resources :species
  resources :antibodies
  root :to => "pages#home"
  match 'about' => "pages#about"
  match 'upload' => "pages#upload"
  match 'create_validator' => "pages#create_validator"
  match 'create_validation' => "pages#create_validation"
  match 'create_target' => "pages#create_target"
  match 'create_source' => "pages#create_source"
  match 'create_antibody' => "pages#create_antibody"
  match 'set_validator' => "pages#set_validator"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="u49Jk-OEJ4rJ5i9Wuhn9QanFNRpgd0ji-_Axd0NqUtY" />
  <title><%= content_for?(:title) ? yield(:title) + " | " : ""%><%= controller.controller_name == "pages" ? controller.action_name.titleize : controller.controller_name.titleize %> | Antibody Validation Database</title>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/combo?3.2.0/build/cssreset/reset-min.css&3.2.0/build/cssfonts/fonts-min.css&3.2.0/build/cssgrids/grids-min.css&3.2.0/build/cssbase/base-min.css">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js"></script>
  <link  href="http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:200,300,400,700&subset=latin" rel="stylesheet" type="text/css" >
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "rails", "application", "autocomplete-rails", "jquery.example.min" %>
  <%= csrf_meta_tag %>
<% if Rails.env == "production" %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-20040168-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
<% end %>
</head>
<body>
<div id="header" class="<%= "home" if request.path == root_path %>">
<h1><%= link_to_unless_current("Antibody Validation Database", root_path) %></h1>
<% if request.path != root_path %>
<div id="search">
  <form method="get" action="<%= targets_url %>" id="searchform">
    <input type="hidden" name="id" id="autocompleted_id">
    <input type="text" name="q" data-autocomplete="<%= autocomplete_target_name_targets_url %>" id_element="#autocompleted_id" value="<%= @q %>" id="target_search_query">
    <input type="submit" value="search" id="searchsubmit">
  </form>
</div>
<% end %>
<div id="navigation">
<ul id="mainmenu" class="horizontal_menu">
  <li><%= link_to_unless_current("Home", root_path) %></li>
  <li><%= link_to("Targets", targets_path, :class => nav_class("targets")) %></li>
  <!-- li><%= link_to("Species", species_index_path, :class => nav_class("species")) %></li -->
  <li><%= link_to("Sources", sources_path, :class => nav_class("sources")) %></li>
  <li><%= link_to("Validators", validators_path, :class => nav_class("validators")) %></li>
  <li><%= link_to("Projects", projects_path, :class => nav_class("projects")) %></li>
  <li><%= link_to_unless_current("Upload", upload_path) %></li>
  <li class="about"><%= link_to_unless_current("About", about_path) %></li>
</ul>
</div>
<% if controller.controller_name == "pages" and controller.action_name == "upload" %>
  <ul id="usermenu" class="horizontal_menu">
  <% if user_signed_in? %>
    <li>Signed in: <%= link_to_unless_current("#{current_user.email}", current_user) %>
      <% if current_user.validator_id.nil? %>
        [<%= link_to "Set up your validating lab", set_validator_url %>]
      <% else %>
        (<%= link_to current_user.validator.name, set_validator_url %>)
      <% end %>
    </li>
    <li><%= link_to_unless_current("Sign out", destroy_user_session_path) %></li>
  <% else %>
    <li><%= link_to_unless_current('Sign in', new_user_session_path)  %></li>
    <li><%= link_to_unless_current('Sign up', new_user_registration_path) %></li>
  <% end %>
  </ul>
<% end %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="main">
<%= yield %>
</div>


<div id="footer">
  Copyright &copy; 2010. Park Lab. All rights reserved.
</div>
</body>
</html>